#!/bin/sh

# The various escape codes that we can use to color our prompt.
			 BOLD=$(tput bold)
        RED="\[\033[1;31m\]"
     YELLOW="\[\033[38;5;221m\]"
      GREEN="\[\033[1;32m\]"
       BLUE="\[\033[38;5;27m\]"
  LIGHT_RED="\[\033[1;31m\]"
LIGHT_BOLD_CYAN="\[\033[38;5;51m\]"
LIGHT_GREEN="\[\033[38;5;208m\]"
      WHITE="\[\033[1;37m\]"
 LIGHT_GRAY="\[\033[0;37m\]"
 COLOR_NONE="\[\e[0m\]"
