# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Directory to save downloads to. If unset, a sensible OS-specific
# default is used.
# Type: Directory
c.downloads.location.directory = '~/dwns'

# Editor (and arguments) to use for the `open-editor` command. The
# following placeholders are defined: * `{file}`: Filename of the file
# to be edited. * `{line}`: Line in which the caret is found in the
# text. * `{column}`: Column in which the caret is found in the text. *
# `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
# Same as `{column}`, but starting from index 0.
# Type: ShellCommand
c.editor.command = ['st', '-e', 'vim', '{file}']

# Characters used for hint strings.
# Type: UniqueCharString
c.hints.chars = 'aoeuidhtns'

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://start.duckduckgo.com'

# Edit url
config.bind(',ed', 'edit-url')

# url.searchengines
c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'i':'https://duckduckgo.com/?q={}&iar=images&iax=images&ia=images',
    'vic':'https://la.wikipedia.org/w/index.php?search={}&title=Specialis%3AQuaerere',
    'red': 'https://reddit.com/r/{}',
    'w3': 'https://www.w3schools.com/?search={}',
    'wt':'http://en.wiktionary.org/?search={}',
    'osm':'http://www.openstreetmap.org/search?query={}',
    'aw':'https://wiki.archlinux.org/index.php?title=Special%3ASearch&search={}',
    'yt':'https://www.youtube.com/results?search_query={}',
    'vw':'http://vim.wikia.com/wiki/Special:Search?fulltext=Search&query={}',
    'mdbg':'https://mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb={}',
    'mysql':'https://dev.mysql.com/doc/search/?d=&p=1&q={}',
    'gm':'https://www.google.com/maps/search/{}',
    'gh':'https://github.com/search?utf8=%E2%9C%93&q={}',
    'wk':'https://en.wikipedia.org/wiki/{}',
}
